'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import * as Dialog from '@radix-ui/react-dialog';
import {Bell,Warning,Drop,Lightning,Trash,CheckCircle,X,ArrowUpRight} from '@phosphor-icons/react';
import {api,scoped,mutation,time,number,type Principal,type Row,type World} from '../lib/api';
import './notifications.css';

type Feed={alerts:Row[];actions:Row[];open_count:number;truncated:boolean;as_of:string;demo_enabled:boolean;zones:{code:string;name:string}[]};
const severityOrder:Record<string,number>={critical:0,high:1,medium:2,low:3,info:4};
const iconFor=(kind:string)=>kind==='water'?Drop:kind==='energy'?Lightning:kind==='waste'?Trash:Warning;
export default function Notifications({user,world,refresh,demoEnabled,onChange}:{user:Principal;world:World;refresh:number;demoEnabled:boolean;onChange:()=>void}){
 const[open,setOpen]=useState(false),[feed,setFeed]=useState<Feed|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(''),[zone,setZone]=useState(''),[filter,setFilter]=useState('all'),[toast,setToast]=useState<Row|null>(null),[read,setRead]=useState<string[]>([]),[updated,setUpdated]=useState('');
 const seen=useRef<Set<string>|null>(null),abort=useRef<AbortController|null>(null),storageKey=`greenops-notifications:${user.id}:${world.id}`;
 const canDrill=demoEnabled&&['hospital_admin','organization_admin','operations_supervisor'].includes(user.role);
 useEffect(()=>{try{setRead(JSON.parse(sessionStorage.getItem(storageKey)||'[]'))}catch{setRead([])}},[storageKey]);
 const load=useCallback(async()=>{
  abort.current?.abort();const controller=new AbortController();abort.current=controller;
  try{const result=await api<Feed>(scoped('/notifications',world.id),{signal:controller.signal});if(controller.signal.aborted)return;
   const next=new Set(result.alerts.map(a=>a.id));if(seen.current){const fresh=result.alerts.find(a=>a.status==='open'&&!seen.current!.has(a.id));if(fresh)setToast(fresh)}seen.current=next;
   setFeed(result);setError('');setUpdated(new Date().toISOString());setZone(old=>result.zones.some(z=>z.code===old)?old:(result.zones.find(z=>z.code==='WARD_A')?.code||result.zones[0]?.code||''));
  }catch(e:any){if(!controller.signal.aborted)setError(e.message)}
 },[world.id]);
 useEffect(()=>{load();const timer=setInterval(()=>{if(document.visibilityState==='visible')load()},30000);return()=>{clearInterval(timer);abort.current?.abort()}},[load,world.as_of,refresh]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),7000);return()=>clearTimeout(timer)},[toast]);
 function mark(ids:string[]){setRead(old=>{const next=Array.from(new Set([...old,...ids])).slice(-500);sessionStorage.setItem(storageKey,JSON.stringify(next));return next})}
 async function drill(kind:string){setBusy(kind);setError('');try{const row=await mutation<Row>('/demo/alerts',world.id,{kind,zone_code:zone});setToast(row);seen.current?.add(row.id);await load();onChange()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function transition(row:Row,operation:string){setBusy(row.id);setError('');try{await mutation(`/demo/alerts/${row.id}/transition`,world.id,{operation,expected_version:row.version});mark([row.id]);await load();onChange()}catch(e:any){setError(e.message)}finally{setBusy('')}}
 const unread=feed?.alerts.filter(a=>a.status==='open'&&!read.includes(a.id)).length||0;
 const alerts=(feed?.alerts||[]).filter(a=>filter==='unread'?a.status==='open'&&!read.includes(a.id):filter==='drills'?a.data.demo_drill:true).sort((a,b)=>(a.status==='resolved'?1:0)-(b.status==='resolved'?1:0)||(severityOrder[a.severity]??4)-(severityOrder[b.severity]??4));
 const mapLink=(a:Row)=>`/campus?zone=${encodeURIComponent(a.zone_code||'')}&layer=${['energy','water','waste'].includes(a.category)?a.category:'heat'}`;
 return <><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="notification-bell" aria-label={`Notifications${unread?`, ${unread} unread`:''}`}><Bell size={20}/>{unread>0&&<span>{unread>99?'99+':unread}</span>}{error&&<i title="Notification feed unavailable"/>}</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="notification-overlay"/><Dialog.Content className="notification-drawer">
  <div className="notification-heading"><div><p className="eyebrow">GREENOPS / OPERATING SIGNALS</p><Dialog.Title>Notification centre</Dialog.Title><Dialog.Description>Recorded risks, upcoming work and presentation drills.</Dialog.Description></div><Dialog.Close asChild><button aria-label="Close notifications"><X size={19}/></button></Dialog.Close></div>
  <div className="notification-summary"><div><strong>{feed?.open_count??'—'}</strong><span>Open risks</span></div><div><strong>{unread}</strong><span>Unread in this session</span></div><div><strong>{feed?.actions.length??'—'}</strong><span>Due within 24 h / overdue</span></div></div>
  <div className="notification-meta"><span>{world.code} · virtual clock</span><button disabled={!feed} onClick={()=>mark(feed!.alerts.map(a=>a.id))}>Mark all read</button><button onClick={load}>Refresh signals</button></div>
  {error&&<p className="notice error" role="alert">Signals unavailable: {error}</p>}
  {canDrill&&<section className="notification-drill"><span className="badge">PRESENTATION DEMO</span><h3>Show an incident from signal to response.</h3><p>Inject a synthetic event, find the building, acknowledge it, then demonstrate containment.</p><label>Reporting zone<select aria-label="Drill reporting zone" value={zone} onChange={e=>setZone(e.target.value)}>{feed?.zones.map(z=><option key={z.code} value={z.code}>{z.code} · {z.name}</option>)}</select></label><div className="notification-drill-buttons">{[['water','Leak drill',Drop],['energy','Energy drill',Lightning],['waste','Pickup drill',Trash]].map(([kind,label,Icon]:any)=><button key={kind} disabled={!!busy||!zone} onClick={()=>drill(kind)}><Icon size={17}/>{busy===kind?'Starting…':label}</button>)}</div><small>These events are simulated. No sensor reading, physical repair, or measured saving is created.</small></section>}
  <div className="notification-tabs" role="group" aria-label="Notification filter">{[['all','All signals'],['unread','Unread'],['drills','Demo drills']].map(([key,label])=><button key={key} aria-pressed={filter===key} onClick={()=>setFilter(key)}>{label}</button>)}</div>
  {!feed&&!error&&<p role="status">Loading authorized signals…</p>}{feed?.truncated&&<p className="notice">Showing the latest 50 open risks. Open the resource ledger for the complete history.</p>}
  <div className="notification-list">{alerts.map(a=>{const Icon=iconFor(a.category),demo=a.data.demo_drill,stage=a.data.stage||'detected';return <article key={a.id} className={'notification-card '+(a.status==='resolved'?'resolved':'')+(!read.includes(a.id)?' unread':'')}><div className="notification-card-title"><span className={'notification-icon '+a.category}><Icon size={19}/></span><div><strong>{a.name}</strong><p>{a.zone_code||'Facility'} · {time(a.event_at)} IST</p></div><span className={'badge '+(a.status==='resolved'?'':'warning')}>{a.status==='resolved'?'Demo contained':a.severity}</span></div>{demo&&<><span className="notification-demo-label">SIMULATED EVENT</span><p>{a.data.message}</p><p className="notification-assumption">{a.data.assumption}</p>{a.data.recorded_context&&<div className="notification-recorded"><span>RECORDED ZONE DATA / LAST 24 HOURS</span><strong>{number(a.data.recorded_context.value)} {a.data.recorded_context.unit}</strong><small>{number(a.data.recorded_context.coverage_pct,0)}% coverage · {a.data.recorded_context.valid_rows}/{a.data.recorded_context.expected_rows} valid intervals · synthetic observations</small><small>{time(a.data.recorded_context.start)} – {time(a.data.recorded_context.end)} IST</small></div>}<ol className="notification-timeline" aria-label="Drill response progress">{[['detected','Signal'],['acknowledged','Acknowledged'],['resolved','Demo contained']].map(([key,label],i)=><li key={key} className={i<=['detected','acknowledged','resolved'].indexOf(stage)?'done':''}><CheckCircle size={14}/>{label}</li>)}</ol></>}{!demo&&<p>Recorded {a.category||'operating'} risk. Inspect its evidence before deciding on a response.</p>}<div className="notification-card-actions"><Link href={mapLink(a)} onClick={()=>{mark([a.id]);setOpen(false)}}>Locate on 3D map <ArrowUpRight size={14}/></Link><Link href="/actions" onClick={()=>setOpen(false)}>Action centre</Link>{!read.includes(a.id)&&<button onClick={()=>mark([a.id])}>Mark read</button>}{demo&&canDrill&&stage==='detected'&&<button className="primary" disabled={!!busy} onClick={()=>transition(a,'acknowledge')}>Acknowledge drill</button>}{demo&&canDrill&&stage==='acknowledged'&&<button className="primary" disabled={!!busy} onClick={()=>transition(a,'resolve')}>Simulate containment</button>}</div><details><summary>Recorded evidence & source</summary><pre className="data">{JSON.stringify(a.data,null,2)}</pre><small>{a.source_type} · record {a.id.slice(0,8)}</small></details></article>})}{feed&&!alerts.length&&<p className="empty">No signals in this filter. Start a demo drill to rehearse the response.</p>}</div>
  {filter==='all'&&!!feed?.actions.length&&<section className="notification-work"><h3>Upcoming & overdue work</h3>{feed.actions.map(a=><Link key={a.id} href="/actions" onClick={()=>setOpen(false)}><span>{a.name}<small>{a.zone_code||'Facility'} · {a.due_at?time(a.due_at)+' IST':''}</small></span><span className="badge">{a.status}</span></Link>)}</section>}
  <footer className="notification-footer">{updated?`Last checked ${new Date(updated).toLocaleTimeString()}`:'Awaiting first check'} · Checks every 30 s while visible. Read status is per browser session. Due dates use the world clock.</footer>
 </Dialog.Content></Dialog.Portal></Dialog.Root>{toast&&<div className="notification-toast" role="status" aria-live="polite"><span className="notification-icon"><Warning size={21}/></span><div><small>{toast.data.demo_drill?'DEMO DRILL / SIMULATED':'NEW RECORDED RISK'}</small><strong>{toast.name}</strong><span>{toast.zone_code||'Facility'} · {toast.severity}</span><button onClick={()=>{setOpen(true);setToast(null)}}>Review signal <ArrowUpRight size={13}/></button></div><button aria-label="Dismiss notification" onClick={()=>setToast(null)}><X size={16}/></button></div>}</>;
}
