'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {ChartLine,Drop,Trash,ArrowUpRight} from '@phosphor-icons/react';
import {api,scoped,World,number,time} from '../lib/api';
import Chart from './chart';

type Resource={metric:string;label:string;unit:string;value:number|null;lower:number|null;upper:number|null;status:string;points:any[];zones:{zone:string;value:number|null;forecast_hours:number;status:string}[];forecast_hours:number;history_coverage_pct:number;last_24h:{value:number|null;coverage_pct:number};change_pct:number|null};
type Forecast={world_id:string;world_version:number;as_of:string;forecast_date:string;timezone:string;start:string;end:string;horizon_hours:number;history_start:string;history_end:string;history_days:number;zone_codes:string[];resources:Resource[];method:string;source_type:string;limitations:string[];boundary:string};
export default function TomorrowForecast({world,refresh}:{world:World;refresh:number}){
 const [data,setData]=useState<Forecast|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState('energy.interval_kwh');
 useEffect(()=>{
  const controller=new AbortController();setData(null);setError('');
  api<Forecast>(scoped('/forecasts/tomorrow',world.id),{signal:controller.signal}).then(r=>{if(!controller.signal.aborted)setData(r)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});
  return()=>controller.abort();
 },[world.id,world.version,world.as_of,refresh]);
 if(error)return <p className="notice error" role="alert">Tomorrow’s forecast could not load: {error}</p>;
 if(!data)return <section className="panel"><p role="status" className="muted">Reading recent hospital history and calculating tomorrow’s resource forecast…</p></section>;
 const active=data.resources.find(r=>r.metric===selected)||data.resources[0];
 const date=new Intl.DateTimeFormat('en-IN',{dateStyle:'full',timeZone:data.timezone}).format(new Date(data.start));
 const icons=[ChartLine,Drop,Trash];
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`greenops-forecast-${data!.forecast_date}.json`;link.click();URL.revokeObjectURL(url)}
 return <div className="page-grid tomorrow-forecast">
  <section className="panel forecast-intro"><div><p className="eyebrow">Next hospital day • {data.timezone}</p><h2>{date}</h2><p className="muted">An estimate from the last {data.history_days} days of authorized energy, water and waste readings.</p><span className="badge">Historical baseline forecast</span></div><button onClick={download}>Export forecast</button></section>
  <div className="grid three forecast-cards">{data.resources.map((r,i)=>{const Icon=icons[i];return <section className="panel" key={r.metric} data-resource={r.metric}><div className="panel-head"><h2>{r.label}</h2><Icon size={23}/></div><span className="tiny muted">Expected tomorrow</span><div className="value forecast-value">{number(r.value)} <small>{r.unit}</small></div>{r.status==='available'?<><p className="tiny">Historical variation: {number(r.lower)}–{number(r.upper)} {r.unit}</p><p className="forecast-change">{r.change_pct===null?'Comparison unavailable for a partial or empty previous period':`${r.change_pct>=0?'+':''}${number(r.change_pct)}% vs last 24 hours`}</p></>:<p className="notice">Insufficient or stale history for every zone and hour. A complete total is unavailable.</p>}<div className="forecast-card-foot"><span>{r.forecast_hours}/{data.horizon_hours} forecast hours</span><span>{number(r.history_coverage_pct)}% history coverage</span></div></section>})}</div>
  <section className="panel"><div className="panel-head"><h2>Tomorrow, hour by hour</h2><span className="badge">{data.horizon_hours} hourly intervals</span></div><div className="tabs" aria-label="Forecast resource">{data.resources.map(r=><button key={r.metric} aria-pressed={r.metric===selected} className={r.metric===selected?'selected':''} onClick={()=>setSelected(r.metric)}>{r.label}</button>)}</div><Chart items={active.points} unit={active.unit}/><p className="tiny muted">Each point estimates consumption or generated waste for the hour ending at that time. Missing forecasts remain gaps. The daily range sums historical hourly variation and is not a confidence interval.</p><details><summary className="details-link">Hourly estimates and historical ranges</summary><div className="table-wrap"><table><thead><tr><th>Hour ending</th><th>Expected {active.unit}</th><th>Historical range</th><th>Zone coverage</th></tr></thead><tbody>{active.points.map(p=><tr key={p.time}><td>{time(p.time,data.timezone)}</td><td>{number(p.value,2)}</td><td>{p.lower===null?'Unavailable':`${number(p.lower,2)}–${number(p.upper,2)} ${active.unit}`}</td><td>{p.available_zones}/{p.expected_zones}</td></tr>)}</tbody></table></div></details></section>
  <section className="panel"><div className="panel-head"><h2>Where tomorrow’s demand comes from</h2><Link className="text-link" href="/campus">Open 3D campus <ArrowUpRight size={12}/></Link></div><div className="table-wrap"><table><thead><tr><th>Reporting zone</th>{data.resources.map(r=><th key={r.metric}>{r.label} ({r.unit})</th>)}</tr></thead><tbody>{data.zone_codes.map(zone=><tr key={zone}><td className="record-title">{zone.replaceAll('_',' ')}</td>{data.resources.map(r=><td key={r.metric}>{number(r.zones.find(z=>z.zone===zone)?.value,2)}</td>)}</tr>)}</tbody></table></div></section>
  <section className="panel"><h2>Forecast evidence</h2><p className="tiny muted">History: {time(data.history_start,data.timezone)} to {time(data.history_end,data.timezone)}. Cutoff: {time(data.as_of,data.timezone)} • World version {data.world_version} • Method: {data.method}.</p><p>{data.boundary}</p><details><summary className="details-link">How this forecast works</summary>{data.limitations.map(line=><p className="tiny muted" key={line}>{line}</p>)}</details><p className="notice">These estimates use existing synthetic observations. Extra visitors and disruptions belong in <Link className="text-link" href="/simulations">What-if Studio</Link>. Water consumption and energy usage are demand; waste here means generated solid waste.</p></section>
 </div>
}
